### ISSUE TITLE
add requirements.txt for Library dependency management

### ISSUE THREAD

**Issue by jheloper** [RittmanMead/md_to_conf#8]
Hi, Thank you for providing a good program!

I'm using this program very well.
By the way, there is one suggestion.
I need a library to run the program, do not you want to manage it as a file?
For example, frequently used requirements.txt.

If you do not mind, I am edit it and pull request.
Thank you again.

**Comment by bhundven** [comment]
The requirements.txt was added the day before this issue was opened. This can probably be closed.
